export const INICIAR_SESION = 'INICIAR_SESION';
export const LOGIN_INVALIDO = 'LOGIN_INVALIDO';
export const AUTENTICACION_VALIDA = 'AUTENTICACION_VALIDA';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const TRAER_HEROES_API = 'TRAER_HEROES_API';
export const AGREGAR_SUPERHEROE_EQUIPO = 'AGREGAR_SUPERHEROE_EQUIPO';
export const ELIMINAR_SUPERHEROE_EQUIPO = 'ELIMINAR_SUPERHEROE_EQUIPO';
export const ACTUALIZAR_ESTADISTICAS_EQUIPO = 'ACTUALIZAR_ESTADISTICAS_EQUIPO';
export const ACTUALIZAR_ESTADISTICA_MAXIMA = 'ACTUALIZAR_ESTADISTICA_MAXIMA';